name: sudden kernel panic
description: sexy problems need sexy solutions
baseurl: /
url: blog.bin7me.de
markdown: kramdown
redcarpet:
  extensions: ["fenced_code_blocks","tables","no_intra_emphasis","autolink","superscript"]
highlighter: rouge
gems: [jekyll-paginate]
author:
  name: Michael Schätzlein
  google_plus: 106482422835272164694 
  twitter: mschaetzlein
  github: bin7me
paginate: 5
excerpt_separator: <!--more-->
navigation:
  - text: index
    title: zurück zum Start
    url: /index.html
  - text: archiv
    title: archiv
    url: /archiv.html
  - text: about
    title: über mich
    url: /about.html
  - text: feed
    title: rss feed
    url: /feed.xml

theme: jekyll-theme-minimal